export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const FETCH_TUTOR_REQUEST = 'FETCH_TUTOR_REQUEST'
export const FETCH_TUTOR_SUCCESS = 'FETCH_TUTOR_SUCCESS'
export const FETCH_TUTOR_FAILURE = 'FETCH_TUTOR_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const GETUSER_REQUEST = 'GETUSER_REQUEST';
export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const GETUSER_FAILURE = 'GETUSER_FAILURE';

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const CREATE_TUTOR_REQUEST = 'CREATE_TUTOR_REQUEST'
export const CREATE_TUTOR_SUCCESS = 'CREATE_TUTOR_SUCCESS'
export const CREATE_TUTOR_FAILURE = 'CREATE_TUTOR_FAILURE'
