export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const FETCH_TUTOR_REQUEST = 'FETCH_TUTOR_REQUEST';
export const FETCH_TUTOR_SUCCESS = 'FETCH_TUTOR_SUCCESS';
export const FETCH_TUTOR_FAILURE = 'FETCH_TUTOR_FAILURE';

export const GET_USER_TUTORS_REQUEST = 'GET_USER_TUTORS_REQUEST';
export const GET_USER_TUTORS_SUCCESS = 'GET_USER_TUTORS_SUCCESS';
export const GET_USER_TUTORS_FAILURE = 'GET_USER_TUTORS_FAILURE';