export const topics = [
    'English ',
    'Physics',
    'Chemistry',
    'Biology',
    'History',
    'Geography',
    'Political Science',
    'Economics',
    'Computer Science',
    'Art',
    'Music',
    'Physical Education',
    'Psychology',
    'Sociology',
    'Philosophy',
    'Environmental Science',
    'Business Studies',
    'Foreign Languages',
    'Health Education',
    'Graphic Design',
    'Engineering',
    'Medicine',
    'Nursing',
    'Accounting',
    'Anthropology',
    'Archaeology',
    'Astronomy',
    'Biochemistry',
    'Botany',
    'Civics',
    'Classical Studies',
    'Communication Studies',
    'Criminal Justice',
    'Dance',
    'Drama',
    'Earth Science',
    'East Asian Studies',
    'European Studies',
    'Film Studies',
    'Finance',
    'Fine Arts',
    'Forensic Science',
    'Gender Studies',
    'Genetics',
    'Geology',
    'Human Resource Management',
    'Information Technology',
    'International Relations',
    'Journalism',
    'Law',
    'Linguistics',
    'Management',
    'Marketing',
    'Math',
    'Meteorology',
    'Microbiology',
    'Middle Eastern Studies',
    'Military Science',
    'Modern Languages',
    'Molecular Biology',
    'Music Theory',
    'Mythology',
    'Neuroscience',
    'Nuclear Physics',
    'Nutrition',
    'Oceanography',
    'Optometry',
    'Paleontology',
    'Pathology',
    'Pharmacology',
    'Philosophy of Science',
    'Photography',
    'Physical Therapy',
    'Physics and Astronomy',
    'Physiology',
    'Political Economy',
    'Public Administration',
    'Public Health',
    'Public Relations',
    'Religious Studies',
    'Robotics',
    'Russian Studies',
    'Social Work',
    'Sociobiology',
    'Space Sciences',
    'Statistics',
    'Theatre Arts',
    'Theology',
    'Urban Studies',
    'Veterinary Medicine',
    'Virology',
    'Women’s Studies',
    'Zoology',
    'Agricultural Sciences',
    'Aquaculture',
    'Conservation Biology',
    'Ecosystem Science',
    'Entomology',
    'Horticulture',
    'Soil Science',
    'Wildlife Management'
];
